### ISSUE TITLE
[FEAT] Add host uptime to observed host object

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/lattice-observer#17]
Right now, the event processor uses the timestamp of the first host heartbeat to record the `first_seen` value of a host. This can differ wildly depending on when the host started and when the lattice observer discovered it. In addition to tracking these values, it would be valuable to know the absolute uptime for the host.

This will also require adding the uptime to the host heartbeat in the [wasmcloud-otp](https://github.com/wasmCloud/wasmcloud-otp) repo.

References
- Using timestamp: https://github.com/wasmCloud/lattice-observer/blob/723fb0dfb57ba5aa831d8663ebd8df43cffd4e08/lib/lattice_observer/observed/lattice.ex#L132
- control interface uptime: https://github.com/wasmCloud/wasmcloud-otp/blob/main/host_core/lib/host_core/control_interface/server.ex#L31-L37

(cc @autodidaddict for thoughts)

**Comment by connorsmith256** [comment]
Resolved by https://github.com/wasmCloud/lattice-observer/pull/29
